accounts/urls.py
#!/usr/bin/python3.12
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views


app_name = "accounts"
urlpatterns = [
    # Include default auth urls.
    path("", include("django.contrib.auth.urls")),
    # Registration page.
    path("register/", views.register, name="register"),
]

alpha_two/urls.py
#!/usr/bin/python3.12
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("site_surveys.urls")),
]

site_surveys/urls.py
#!/usr/bin/python3.12
"""Defines URL patterns for site surveys."""
from django.urls import path

from . import views


app_name = "site_surveys"
urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    # Page that shows all sites.
    path("sites/", views.sites, name="sites"),
    path("useful_links/", views.useful_links, name="useful_links"),
    path("documentation/", views.documentation, name="documentation"),
    path("contacts/", views.contacts, name="contacts"),
    path("about/", views.about, name="about"),
    # Detail page for a single site.
    path("sites/<slug:site_id>/", views.site, name="site"),
    # Page for adding a new site.
    path("new_site/", views.new_site, name="new_site"),
    # Page for editing an entry.
    path("edit_site/<int:site_id>/", views.edit_site, name="edit_site"),
    path("photo_checklist/<int:site_id>/", views.photo_checklist, name="photo_checklist"),
    path("network_checklist/<int:site_id>/", views.network_checklist, name="network_checklist"),
    path("server_checklist/<int:site_id>/", views.server_checklist, name="server_checklist"),
    path("mdf_checklist/<int:site_id>/", views.mdf_checklist, name="mdf_checklist"),
    path("idf_checklist/<int:site_id>/", views.idf_checklist, name="idf_checklist"),
    path('export_all_sites/', views.export_all_sites, name='export_all_sites'),
    path('export_site/<int:site_id>/', views.export_site, name='export_site'),
    path('download_file/<int:site_id>/', views.download_file, name='download_file'),
    path('search_results/', views.SearchResultsView.as_view(), name='search_results'),
]

site_surveys/forms.py
#!/usr/bin/python3.12
from django import forms

from .models import Site


# INTEGER_CHOICES = [tuple([x, x]) for x in range(1, 99)]


class SiteForm(forms.ModelForm):
    title = forms.CharField(
        label="",
        required=True,
        min_length=4,
        max_length=4,
        widget=forms.TextInput(attrs={'placeholder': 'Site ID', 'style': 'width: 300px;'}),
    )
    first_name = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'First Name', 'style': 'width: 300px;'})
    )
    last_name = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'Last Name', 'style': 'width: 300px;'})
    )
    email = forms.EmailField(
        label="",
        widget=forms.EmailInput(attrs={'placeholder': 'Email', 'style': 'width: 300px;'})
    )
    street_address = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'Street Address', 'style': 'width: 300px;'})
    )
    city = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'City', 'style': 'width: 300px;'})
    )
    state = forms.CharField(
        label="",
        widget=forms.Select(choices=Site.STATE, attrs={'placeholder': 'State', 'style': 'width: 300px;'}),
    )
    zip_code = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': 'ZIP Code', 'style': 'width: 300px;'})
    )
    site_type = forms.CharField(
        label="",
        required=False,
        widget=forms.Select(choices=Site.SITE_TYPES),
    )
    file_upload = forms.FileField(
        label="Select",
        required=False,
    )

    class Meta:
        model = Site
        fields = ["title", "first_name", "last_name", "email", "street_address", "city", "state", "zip_code", "site_type", "file_upload"]


# class FileUploadForm(forms.ModelForm):
#     class Meta:
#         model = Site
#         fields = ["file_upload"]


class PhotoForm(forms.ModelForm):
    front = forms.CharField(
        label="Front",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )
    back = forms.CharField(
        label="Back",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )
    left = forms.CharField(
        label="Left",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )
    right = forms.CharField(
        label="Right",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )

    class Meta:
        model = Site
        fields = ["front", "back", "left", "right"]


class NetworkForm(forms.ModelForm):
    router_one = forms.CharField(
        label="Router One",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )
    router_two = forms.CharField(
        label="Router Two",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )
    switch_one = forms.CharField(
        label="Switch One",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )
    switch_two = forms.CharField(
        label="Switch Two",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )

    class Meta:
        model = Site
        fields = ["router_one", "router_two", "switch_one", "switch_two"]


class ServerForm(forms.ModelForm):
    server_one = forms.CharField(
        label="Server One",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )
    server_two = forms.CharField(
        label="Server Two",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )

    class Meta:
        model = Site
        fields = ["server_one", "server_two"]


class MDFForm(forms.ModelForm):
    mdf = forms.CharField(
        label="MDF",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )

    class Meta:
        model = Site
        fields = ["mdf"]


class IDFForm(forms.ModelForm):
    idf = forms.CharField(
        label="IDF",
        required=False,
        widget=forms.Select(choices=Site.YES_NO_CHOICES),
    )

    class Meta:
        model = Site
        fields = ["idf"]

site_surveys/views.py
#!/usr/bin/python3.12
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, FileResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.db.models import Q

from csv import writer

from .models import Site
from .forms import SiteForm, PhotoForm, NetworkForm, ServerForm, MDFForm, IDFForm


def index(request):
    """The home page for Site Surveys."""
    return render(request, "site_surveys/index.html")


@login_required
def sites(request):
    """Show all sites."""
    sites = Site.objects.order_by("title")
    count = sites.count()

    # Pagination with 3 posts per page
    paginator = Paginator(sites, 10)
    page_number = request.GET.get("page", 1)
    try:
        site = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer deliver the first page
        site = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        site = paginator.page(paginator.num_pages)
    context = {"sites": site, "count": count}
    return render(request, "site_surveys/sites.html", context)


@login_required
def site(request, site_id):
    """Show a single site and all of its notes."""
    try:
        # site = Site.objects.get(id=site_id)
        site = get_object_or_404(Site, slug=site_id)
        # # Make sure the site belongs to the current user.
        # if site.owner != request.user:
        #     raise Http404

        context = {
            "site": site
        }
        return render(request, "site_surveys/site.html", context)

    except:
        return redirect("site_surveys:sites")


@login_required
def new_site(request):
    """Add a new site."""
    if request.method != "POST":
        # No data submitted; create a blank form.
        site_form = SiteForm()
    else:
        # POST data submitted; process data.
        site_form = SiteForm(request.POST, request.FILES)
        if site_form.is_valid():
            new_site = site_form.save(commit=False)
            new_site.owner = request.user
            new_site.save()
            return redirect("site_surveys:sites")

    # Display a blank or invalid form.
    context = {"site_form": site_form}
    return render(request, "site_surveys/new_site.html", context)


@login_required
def edit_site(request, site_id):
    """Edit an existing site."""
    site = get_object_or_404(Site, id=site_id)

    if request.method != "POST":
        # No data submitted; create a blank form.
        site_form = SiteForm(instance=site)

    else:
        # POST data submitted; process data.
        site_form = SiteForm(instance=site, data=request.POST, files=request.FILES)
        if site_form.is_valid():
            site_form.save()
            context = {"site": site}
            return render(request, "site_surveys/site.html", context)

    # Display a blank or invalid form.
    context = {"site": site, "site_form": site_form}
    return render(request, "site_surveys/edit_site.html", context)


@login_required
def photo_checklist(request, site_id):
    """Edit an existing site."""
    site = get_object_or_404(Site, id=site_id)

    if request.method != "POST":
        # No data submitted; create a blank form.
        photo_form = PhotoForm(instance=site)

    else:
        # POST data submitted; process data.
        photo_form = PhotoForm(instance=site, data=request.POST, files=request.FILES)
        if photo_form.is_valid():
            photo_form.save()
            context = {"site": site}
            return render(request, "site_surveys/site.html", context)

    # Display a blank or invalid form.
    context = {"site": site, "photo_form": photo_form}
    return render(request, "site_surveys/photo_checklist.html", context)


@login_required
def network_checklist(request, site_id):
    """Edit an existing site."""
    site = get_object_or_404(Site, id=site_id)

    if request.method != "POST":
        # No data submitted; create a blank form.
        network_form = NetworkForm(instance=site)

    else:
        # POST data submitted; process data.
        network_form = NetworkForm(instance=site, data=request.POST, files=request.FILES)
        if network_form.is_valid():
            network_form.save()
            context = {"site": site}
            return render(request, "site_surveys/site.html", context)

    # Display a blank or invalid form.
    context = {"site": site, "network_form": network_form}
    return render(request, "site_surveys/network_checklist.html", context)


@login_required
def server_checklist(request, site_id):
    """Edit an existing site."""
    site = get_object_or_404(Site, id=site_id)

    if request.method != "POST":
        # No data submitted; create a blank form.
        server_form = ServerForm(instance=site)

    else:
        # POST data submitted; process data.
        server_form = ServerForm(instance=site, data=request.POST, files=request.FILES)
        if server_form.is_valid():
            server_form.save()
            context = {"site": site}
            return render(request, "site_surveys/site.html", context)

    # Display a blank or invalid form.
    context = {"site": site, "server_form": server_form}
    return render(request, "site_surveys/server_checklist.html", context)


@login_required
def mdf_checklist(request, site_id):
    """Edit an existing site."""
    site = get_object_or_404(Site, id=site_id)

    if request.method != "POST":
        # No data submitted; create a blank form.
        mdf_form = MDFForm(instance=site)

    else:
        # POST data submitted; process data.
        mdf_form = MDFForm(instance=site, data=request.POST, files=request.FILES)
        if mdf_form.is_valid():
            mdf_form.save()
            context = {"site": site}
            return render(request, "site_surveys/site.html", context)

    # Display a blank or invalid form.
    context = {"site": site, "mdf_form": mdf_form}
    return render(request, "site_surveys/mdf_checklist.html", context)


@login_required
def idf_checklist(request, site_id):
    """Edit an existing site."""
    site = get_object_or_404(Site, id=site_id)

    if request.method != "POST":
        # No data submitted; create a blank form.
        idf_form = IDFForm(instance=site)

    else:
        # POST data submitted; process data.
        idf_form = IDFForm(instance=site, data=request.POST, files=request.FILES)
        if idf_form.is_valid():
            idf_form.save()
            context = {"site": site}
            return render(request, "site_surveys/site.html", context)

    # Display a blank or invalid form.
    context = {"site": site, "idf_form": idf_form}
    return render(request, "site_surveys/idf_checklist.html", context)


@login_required
def export_all_sites(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="export_all_sites.csv"'
    export_sites = Site.objects.all()

    my_writer = writer(response)
    my_writer.writerow([
        "title", "first_name", "last_name", "email", "street_address", "city", "state", "zip_code", "site_type",
        "front", "back", "left", "right", "router_one", "router_two", "switch_one", "switch_two", "server_one",
        "server_two", "mdf", "idf",
    ])

    for export_site in export_sites:
        my_writer.writerow([
            export_site.title,
            export_site.first_name,
            export_site.last_name,
            export_site.email,
            export_site.street_address,
            export_site.city,
            export_site.state,
            export_site.zip_code,
            export_site.site_type,
            export_site.front,
            export_site.back,
            export_site.left,
            export_site.right,
            export_site.router_one,
            export_site.router_two,
            export_site.switch_one,
            export_site.switch_two,
            export_site.server_one,
            export_site.server_two,
            export_site.mdf,
            export_site.idf,
        ])
    return response


@login_required
def export_site(request, site_id):
    export_site = get_object_or_404(Site, id=site_id)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="export_site_{export_site.title}.csv"'

    my_writer = writer(response)
    my_writer.writerow([
        "title", "first_name", "last_name", "email", "street_address", "city", "state", "zip_code", "site_type",
        "front", "back", "left", "right", "router_one", "router_two", "switch_one", "switch_two", "server_one",
        "server_two", "mdf", "idf",
    ])
    my_writer.writerow([
        export_site.title,
        export_site.first_name,
        export_site.last_name,
        export_site.email,
        export_site.street_address,
        export_site.city,
        export_site.state,
        export_site.zip_code,
        export_site.site_type,
        export_site.front,
        export_site.back,
        export_site.left,
        export_site.right,
        export_site.router_one,
        export_site.router_two,
        export_site.switch_one,
        export_site.switch_two,
        export_site.server_one,
        export_site.server_two,
        export_site.mdf,
        export_site.idf,
    ])
    return response


@login_required
def download_file(request, site_id):
    site = get_object_or_404(Site, id=site_id)
    return FileResponse(site.file_upload.open(), as_attachment=True,)


@login_required
def useful_links(request):
    return render(request, "site_surveys/useful_links.html")


@login_required
def documentation(request):
    return render(request, "site_surveys/documentation.html")


@login_required
def contacts(request):
    return render(request, "site_surveys/contacts.html")


@login_required

site_surveys/templates/site_surveys/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Site Surveys</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top mb-5 border" style="background-color: #556278; margin: -1px; height: 50px">
        <div class="container-fluid" style="text-align: center;">
            <a class="navbar-brand" href="{% url 'site_surveys:index' %}">
                <img src="{% static '/site_surveys/images/pnc_logo_five.png' %}" width="70" height="22" class="rounded" alt="Missing Image">
                <h6> Site Surveys</h6>
            </a>
            <button class="navbar-toggler position-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse gap-2" id="navbarCollapse">
                <div class="btn-group ms-auto mb-2 mb-md-0">
                    <button type="button" class="btn dropdown-toggle" style="font-size: small; background-color: #d5dff5; --bs-btn-padding-y: .25rem; --bs-btn-padding-x: 1rem;" data-bs-toggle="dropdown" aria-expanded="false"><strong>&#127974; Sites</strong></button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" style="font-size: small" href="{% url 'site_surveys:sites' %}"><strong>List of Sites</strong></a></li>
                        <li><a class="dropdown-item" style="font-size: small" href="{% url 'site_surveys:new_site' %}"><strong>Add New Site</strong></a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" style="font-size: small" href="#">Separated link</a></li>
                    </ul>
                </div>
                <div class="btn-group ms-auto mb-2 mb-md-0">
                    <button type="button" class="btn dropdown-toggle" style="font-size: small; background-color: #d5dff5; --bs-btn-padding-y: .25rem; --bs-btn-padding-x: 1.2rem;" data-bs-toggle="dropdown" aria-expanded="false"><strong>&#128423; Links</strong></button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" style="font-size: small" href="{% url 'site_surveys:useful_links' %}"><strong>Links</strong></a></li>
                    </ul>
                </div>
                <div class="btn-group ms-auto mb-2 mb-md-0">
                    <button type="button" class="btn dropdown-toggle" style="font-size: small; background-color: #d5dff5; --bs-btn-padding-y: .25rem; --bs-btn-padding-x: 1.2rem;" data-bs-toggle="dropdown" aria-expanded="false"><strong>&#128221; Docs</strong></button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" style="font-size: small" href="{% url 'site_surveys:documentation' %}"><strong>Docs</strong></a></li>
                    </ul>
                </div>
                <div class="btn-group ms-auto mb-2 mb-md-0">
                    <button type="button" class="btn dropdown-toggle" style="font-size: small; background-color: #d5dff5; --bs-btn-padding-y: .25rem; --bs-btn-padding-x: 0.6rem;" data-bs-toggle="dropdown" aria-expanded="false"><strong>&#128222; Contacts</strong></button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" style="font-size: small" href="{% url 'site_surveys:contacts' %}"><strong>Contacts</strong></a></li>
                    </ul>
                </div>
                <div class="btn-group ms-auto mb-2 mb-md-0">
                    <button type="button" class="btn dropdown-toggle" style="font-size: small; background-color: #d5dff5; --bs-btn-padding-y: .25rem; --bs-btn-padding-x: 1rem;" data-bs-toggle="dropdown" aria-expanded="false"><strong>&#128187; About</strong></button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" style="font-size: small" href="{% url 'site_surveys:about' %}"><strong>About</strong></a></li>
                    </ul>
                </div>
                <div class="container-fluid ms-auto mb-2 mb-md-0 g-5">
                    <form class="d-flex" role="search" action="{% url 'site_surveys:search_results' %}" method="get">
                        <input name="q" class="form-control me-2" style="font-size: small; color: black; text-align: left" type="search" placeholder="Search" aria-label="Search">
                    </form>
                </div>

                <!-- Account-related links -->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">

                    {% if user.is_authenticated %}
                        <li class="badge">
                            <h4><span class="badge text-bg-light" style="font-size: small">{{ user.username.title }}</span></h4>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" style="font-size: small" href="{% url 'accounts:register' %}"><h4>Register</h4></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-size: small" href="{% url 'accounts:login' %}"><h4>Log In</h4></a>
                        </li>
                    {% endif %}

                </ul> <!-- End of account-related links -->

                {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method='post'>
                        {% csrf_token %}
                        <button name='submit' class='btn btn-light btn-outline-dark text-dark' data-toggle="tooltip" style="font-size: small; background-color: #FF5400;"
                                data-placement="top" title="Click to log out of site."><strong>&#128274; Logout</strong></button>
                    </form>
                {% endif %}

            </div> <!-- Closes collapsible parts of navbar -->

        </div> <!-- Closes navbar's container -->
    </nav> <!-- End of navbar -->

    <main class="container" style="margin-top: 60px;">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
        <footer>
            <p class="copyright border-top" style="position: sticky; bottom: 0;">&copy Copyright 2024 jwinternet</p>
        </footer>
    </main>

</body>
</html>

site_surveys/templates/site_surveys/site.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Site</title>
</head>
<body>
    {% extends "site_surveys/base.html" %}

    {% block page_header %}

        <div class="container mt-3">
            <h2>{{ site.title.upper }}</h2>
            <h5>General Information (<a href="{% url 'site_surveys:edit_site' site.id %}">edit</a>)</h5>
            <div class="table-responsive">
                <table class="table table-bordered table-striped" style="background-color: #d5dff5;">
                    <thead>
                        <tr>
                            <th>Site ID</th>
                            <th>Date Added</th>
                            <th>Updated</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Street Address</th>
                            <th>City</th>
                            <th>State</th>
                            <th>ZIP Code</th>
                            <th>Site Type</th>
                            <th>File Upload</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ site.title.upper }}</td>
                            <td>{{ site.date_added }}</td>
                            <td>{{ site.updated }}</td>
                            <td>{{ site.first_name }}</td>
                            <td>{{ site.last_name }}</td>
                            <td>{{ site.email }}</td>
                            <td>{{ site.street_address }}</td>
                            <td>{{ site.city }}</td>
                            <td>{{ site.state }}</td>
                            <td>{{ site.zip_code }}</td>
                            <td>{{ site.site_type.title }}</td>
                            <td>{{ site.file_upload }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="container mt-3">
            <h5>Photo Checklist (<a href="{% url 'site_surveys:photo_checklist' site.id %}">edit</a>)</h5>
            <div class="table-responsive">
                <table class="table table-bordered table-striped" style="background-color: #d5dff5;">
                    <thead>
                        <tr>
                            <th>Front</th>
                            <th>Back</th>
                            <th>Left</th>
                            <th>Right</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ site.front }}</td>
                            <td>{{ site.back }}</td>
                            <td>{{ site.left }}</td>
                            <td>{{ site.right }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="container mt-3">
            <h5>Network Checklist (<a href="{% url 'site_surveys:network_checklist' site.id %}">edit</a>)</h5>
            <div class="table-responsive">
                <table class="table table-bordered table-striped" style="background-color: #d5dff5;">
                    <thead>
                        <tr>
                            <th>Router One</th>
                            <th>Router Two</th>
                            <th>Switch One</th>
                            <th>Switch Two</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ site.router_one }}</td>
                            <td>{{ site.router_two }}</td>
                            <td>{{ site.switch_one }}</td>
                            <td>{{ site.switch_two }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="container mt-3">
            <h5>Server Checklist (<a href="{% url 'site_surveys:server_checklist' site.id %}">edit</a>)</h5>
            <div class="table-responsive">
                <table class="table table-bordered table-striped" style="background-color: #d5dff5;">
                    <thead>
                        <tr>
                            <th>Server One</th>
                            <th>Server Two</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ site.server_one }}</td>
                            <td>{{ site.server_two }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="container mt-3">
            <h5>MDF Checklist (<a href="{% url 'site_surveys:mdf_checklist' site.id %}">edit</a>)</h5>
            <div class="table-responsive">
                <table class="table table-bordered table-striped" style="background-color: #d5dff5;">
                    <thead>
                        <tr>
                            <th>MDF</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ site.mdf }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="container mt-3">
            <h5>IDF Checklist (<a href="{% url 'site_surveys:idf_checklist' site.id %}">edit</a>)</h5>
            <div class="table-responsive">
                <table class="table table-bordered table-striped" style="background-color: #d5dff5;">
                    <thead>
                        <tr>
                            <th>IDF</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ site.idf }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div>
            <a href="{% url 'site_surveys:export_site' site.id %}">
                <button type="button" class="button">Export Site Data</button>
            </a>
        </div>
        <div>
            {% if site.file_upload %}
                <a href="{% url 'site_surveys:download_file' site.id %}">
                    <button type="button" class="button">Download Attached File</button>
                </a>
            {% endif %}
        </div>

    {% endblock page_header %}

    {% block content %}

    {% endblock content %}
</body>
</html>

site_surveys/templates/site_surveys/sites.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sites</title>
</head>
<body>
    {% extends "site_surveys/base.html" %}

    {% block page_header %}
        <h2>Sites</h2><h6>Current Total: {{ count }}</h6>
    {% endblock page_header %}

    {% block content %}

        <ul class="list-group border-bottom pb-2 mb-4">
            {% for site in sites %}

                <li class="list-group-item border-1">
                    <div class="p-2 text-light border rounded-2" style="background-color: #455eb5;">
                        <div class="container text-light">
                            <a href="{{ site.get_absolute_url }}" style="color: white"><h5>{{ site.title.upper }}</h5></a>
                            <div style="font-size: small;">Last Updated: {{ site.updated }}</div>
                            <p class="tags" style="font-size: small;"><strong>Tags: {{ site.tags.all|join:", " }}</strong></p>
                        </div>
                    </div>
                </li>

            {% empty %}
                <li class="list-group-item border-0">No sites have been added yet.</li>
            {% endfor %}
        </ul>
        <div><a href="{% url 'site_surveys:export_all_sites' %}">
            <button type="button" class="button">Export All Site Data</button></a></div>
        <br><a href="{% url 'site_surveys:new_site' %}">Add New Site</a>

    {% include "site_surveys/pagination.html" with page=sites %}
        <br>

    {% endblock content %}
</body>
</html>